assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -34,17 +34,41 @@ fi
 if [ -f composer.json ]; then
   echo "Found 'composer.json', installing dependencies using composer.phar... "
 
-  if [ ! -f "./composer.phar" ]
-  then
-    echo "Fetching composer.phar"
-    # Install Composer
-    php -r "readfile('https://getcomposer.org/installer');" | php
-  else
-    echo "Reusing downloaded composer.phar"
+  # Install Composer
+  TEMPFILE=$(mktemp)
+  RETRIES=6
+  for ((i=0; i<$RETRIES; i++)); do
+
+    if [ -z "$COMPOSER_INSTALLER" ]; then
+      export COMPOSER_INSTALLER="https://getcomposer.org/installer"
+    fi
+
+    echo "Downloading $COMPOSER_INSTALLER, attempt $((i+1))/$RETRIES"
+    curl -o $TEMPFILE $COMPOSER_INSTALLER && break
+    sleep 10
+  done
+  if [[ $i == $RETRIES ]]; then
+    echo "Download failed, giving up."
+    exit 1
+  fi
+  php <$TEMPFILE
+
+  if [ "$(ls -a /tmp/artifacts/ 2>/dev/null)" ]; then
+    echo "Restoring build artifacts"
+    mv /tmp/artifacts/* $HOME/
+  fi
+
+  # Change the repo mirror if provided
+  if [ -n "$COMPOSER_MIRROR" ]; then
+    ./composer.phar config -g repositories.packagist composer $COMPOSER_MIRROR
+  fi
+
+  if [ "$COMPOSER_ALLOW_HTTP" = true ]; then
+    ./composer.phar config -g secure-http false
   fi
 
   # Install App dependencies using Composer
-  ./composer.phar install --no-interaction --no-ansi --optimize-autoloader
+  ./composer.phar install --no-interaction --no-ansi --optimize-autoloader $COMPOSER_ARGS
 
   if [ ! -f composer.lock ]; then
     echo -e "\nConsider adding a 'composer.lock' file into your source repository.\n"
@@ -52,4 +76,5 @@ if [ -f composer.json ]; then
 fi
 
 # Fix source directory permissions
-fix-permissions ./
+bash fix-permissions ./
+
